name: fangyuanxiaozhan
on:
  push:
    branches:    
      - main
jobs:
  push:
      runs-on: ubuntu-latest



      steps:
      - uses: actions/checkout@v2 # Checking out the repo

      - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
      

      - name: Install dependencies
        run: |
          python -m pip install -p Pipfile.lock
      
      - name: Build
        env:
            USERNAME: ${{ secrets.USERNAME }}
            PASSWORD: ${{ secrets.PASSWORD }}
            XMLRPC_PHP: ${{ secrets.XMLRPC_PHP }}
        run: |
          python main.py

      - name: Commit and push if changed   # 将.md_sha1 README.md 更新到仓库
        run: |
          git diff
          git config --global user.email "yanghong1484944458@gmail.com"
          git config --global user.name "yanghong"
          git add .md_sha1 README.md
          git commit -m "Github Action auto Updated"
          git push



      # - name: Install dependecies
      #   uses: VaultVulp/action-pipenv@v2.0.1
      #   with:
      #     command: install -d # Install all dependencies, including development ones
      # - name: Build
      #   env:
      #       USERNAME: ${{ secrets.USERNAME }}
      #       PASSWORD: ${{ secrets.PASSWORD }}
      #       XMLRPC_PHP: ${{ secrets.XMLRPC_PHP }}
      #   uses: VaultVulp/action-pipenv@v2.0.1
      #   with:
      #     command: run build
      # - name: Commit and push if changed   # 将.md_sha1 README.md 更新到仓库
      #   run: |
      #     git diff
      #     git config --global user.email "yanghong1484944458@gmail.com"
      #     git config --global user.name "yanghong"
      #     git add .md_sha1 README.md
      #     git commit -m "Github Action auto Updated"
      #     git push